name: PR Security Auto-Assign

on:
  pull_request:
    types: [labeled]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Auto-assign PR
        if: github.event.label.name == 'security'
        uses: actions/github-script@v7.0.1
        with:
          script: |
            console.log('Debug - Event context:', {
              label: github.event.label.name,
              repository: context.repo,
              issue: context.issue,
              payload: github.context.payload
            });
            
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ['tdupoiron']
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
